/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IULibro.java
 *
 * Created on 19-dic-2011, 10:57:37
 */
package GUIBiblioteca;

import Util.imgdevolucion;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import Datos.Lector;
import Datos.Personal;
import Datos.Prestamo;
import Datos.Detalles;
import Datos.Libro;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos J Medina
 */
public class IUDevolucion extends javax.swing.JFrame {

    
ArrayList empleado = new ArrayList();
static String lect;        
static String libr;        
static String cadenaFecha;   
static Detalles oDe= new Detalles();
static Prestamo pre=null;
static int indicel;

private Reloj.Hora hora;
    /** Creates new form IULibro */
    public IUDevolucion() {
        this.setUndecorated(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnatras = new javax.swing.JButton();
        btnlibro = new javax.swing.JButton();
        btnpersonal = new javax.swing.JButton();
        btnprestamo = new javax.swing.JButton();
        btnlector = new javax.swing.JButton();
        btndevolucion = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        btndesarrollador = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblhora = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        btnId = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdes = new javax.swing.JTextArea();
        lblRegistro = new javax.swing.JLabel();
        txtPersonal = new com.guis.autotextfield.AutoTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAtras.png"))); // NOI18N
        btnatras.setBorder(null);
        btnatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        btnlibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnlibro.setBorder(null);
        btnlibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibroActionPerformed(evt);
            }
        });

        btnpersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnpersonal.setBorder(null);
        btnpersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonalActionPerformed(evt);
            }
        });

        btnprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnprestamo.setBorder(null);
        btnprestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamoActionPerformed(evt);
            }
        });

        btnlector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnlector.setBorder(null);
        btnlector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlectorActionPerformed(evt);
            }
        });

        btndevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuActivo.png"))); // NOI18N
        btndevolucion.setBorder(null);
        btndevolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnreportes.setBorder(null);
        btnreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        btndesarrollador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btndesarrollador.setBorder(null);
        btndesarrollador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnPrimero.png"))); // NOI18N
        btnPrimero.setBorder(null);
        btnPrimero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAnterior.png"))); // NOI18N
        btnAnterior.setBorder(null);
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSiguiente.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnUltimo.png"))); // NOI18N
        btnUltimo.setBorder(null);
        btnUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblhora.setBackground(new java.awt.Color(255, 255, 255));
        lblhora.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblhora.setForeground(new java.awt.Color(255, 255, 255));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnEditar.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setDisabledIcon(null);
        btnEditar.setEnabled(false);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnNuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setDisabledIcon(null);
        btnNuevo.setEnabled(false);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnGuardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setDisabledIcon(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnEliminar.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setDisabledIcon(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSalir.png"))); // NOI18N
        btnNuevo1.setBorder(null);
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        btnId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnDoc10.png"))); // NOI18N
        btnId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIdMouseClicked(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnBuscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtbuscar.setText("Buscar....");
        txtbuscar.setBorder(null);

        tblRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lector", "Libro", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tblRes);

        txtdes.setBackground(new java.awt.Color(125, 164, 186));
        txtdes.setColumns(20);
        txtdes.setRows(6);
        txtdes.setText("Ingrese descripcion......");
        txtdes.setAutoscrolls(false);
        txtdes.setBorder(null);
        jScrollPane2.setViewportView(txtdes);

        lblRegistro.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblRegistro.setText("1 DE 20");

        txtPersonal.setText("Nombres y Apellidos (Personal)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnatras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnreportes)
                            .addComponent(btnlibro)
                            .addComponent(btnpersonal)
                            .addComponent(btnprestamo)
                            .addComponent(btndevolucion)
                            .addComponent(btnlector)
                            .addComponent(btndesarrollador))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(btnId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnBuscar))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(lblRegistro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPrimero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAnterior)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSiguiente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUltimo))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnNuevo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEditar)
                                    .addGap(14, 14, 14)
                                    .addComponent(btnGuardar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEliminar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnNuevo1)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnUltimo)
                    .addComponent(btnPrimero)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRegistro)
                        .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnlibro)
                        .addGap(26, 26, 26)
                        .addComponent(btnpersonal)
                        .addGap(25, 25, 25)
                        .addComponent(btnprestamo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnId)
                            .addComponent(btnBuscar)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnlector)
                        .addGap(24, 24, 24)
                        .addComponent(btndevolucion)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreportes)
                    .addComponent(txtPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndesarrollador)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(btnNuevo1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private int estado=1;
    private int estado1=1;
    static int indicep;
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imgdevolucion p = new imgdevolucion();
        this.add( p , BorderLayout.CENTER);
        p.repaint();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        // TODO add your handling code here:
        hora = new Reloj.Hora();/***Inicializar la variable hora***/
        hora.setBounds(0, 0, 150, 15);/*(Ubicacion en eje x, Ubicacion en eje y, Ancho, Alto)*/
       //hora.setFont(new Font("Trebuchet MS",java.awt.Font.BOLD, 10));/*Cambiamos la fuente, estilo y tamaño*/
        this.lblhora.add(hora);/*La agregamos al JFrame*/
        // TODO add your handling code here:
        Date  fechaActual=new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        cadenaFecha = formato.format(fechaActual);
        Iniciar();
    }//GEN-LAST:event_formWindowOpened
    
     public void Iniciar(){
     
        int j=1;
   
        while ( j <= IUPersonal.oPe.obtenerCantidad() ) {
            Personal per=null;
            per= IUPersonal.oPe.buscarPerCod(String.valueOf(j));
            if(per!=null) {
                empleado.add(per.getNom() + " " + per.getApe());
            }
            j++;
        }
        this.txtPersonal.setItems(empleado);
        this.tblRes.setModel(new DefaultTableModel());
    }
     
    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        IUMenu menu=new IUMenu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        this.dispose();
        System.exit(0);
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibroActionPerformed
        IULibro libro=new IULibro();
        libro.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnlibroActionPerformed

    private void btnpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonalActionPerformed
        IUPersonal personal=new IUPersonal();
        personal.setVisible(true);
        this.setVisible(false);
        this.dispose();  
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpersonalActionPerformed

    private void btnIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdMouseClicked
        if (estado==1){
            ImageIcon icon = createImageIcon("../Archivos/btnDoc11.png","Boton para saber si esta disponible");
            this.btnId.setIcon(icon);
            estado=0;
        }else{
            ImageIcon icon = createImageIcon("../Archivos/btnDoc10.png","Boton para saber si esta disponible");
            this.btnId.setIcon(icon);
            estado=1;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnIdMouseClicked

    private void btnprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamoActionPerformed
        IUPrestamo prestamo=new IUPrestamo();
        prestamo.setVisible(true);
        this.setVisible(false);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnprestamoActionPerformed

    private void btnlectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlectorActionPerformed
        IULector lector=new IULector();
        lector.setVisible(true);
        this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_btnlectorActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        IUReportes reportes=new IUReportes();
        reportes.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        String res=null;
        String filtro=this.txtbuscar.getText();
        
        Lector lec=null;
        
        if (estado==1){
        lec= IULector.oLe.buscarLecID(filtro);
        }else{
        lec= IULector.oLe.buscarLecDNI(filtro);
        }
        if(lec!=null) {
        
            res=lec.getNom() + " " + lec.getApe();
            DefaultTableModel datos = new DefaultTableModel();
            
            JTable tabla = new JTable(datos);
            datos.addColumn("Lector");
            datos.addColumn("Libro");
            datos.addColumn("Fecha");
            String fila[];
      
            pre=IUPrestamo.oPr.buscarPreLec(res);
            
            indicep=IUPrestamo.oPr.obtenerIndice(pre);
                if (pre != null){
                        fila =new String [3];
                        fila[0]=pre.getLector();
                        lect=pre.getLector();
                        fila[1]=pre.getLibro();
                        libr=pre.getLibro();
                        fila[2]=pre.getFecha();
                        datos.addRow(fila);
                        tabla.updateUI();
                }              
            tblRes.setModel(datos);
        }else{
            this.txtbuscar.setText("0 Resultados");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //Variables propias del metodo
        String per,des;
        boolean ex;

        per=this.txtPersonal.getText();
        des=this.txtdes.getText();
        
        Detalles d=new Detalles(cadenaFecha,libr,lect,per,des);
        ex= oDe.agregarDetalle(d); //Guarda el obj. en la Coleccion
            
        if(ex==true) {
            //para dar de baja el prestamo
            pre.setEstado("CORRECTO");
            IUPrestamo.oPr.modificarPre(indicep, pre);
            
            //para regresar el estado del libro a disponible
             Libro lib=null;
        
            lib=IULibro.oLi.buscarLibNom(libr);
            System.out.println(libr);
            indicel=IULibro.oLi.obtenerIndice(lib);

            lib.setDis(true);
            IULibro.oLi.modificarLib(indicel, lib);
                
            IUMsg msg=new IUMsg();
            msg.setVisible(true);
            this.btnGuardar.setEnabled(false);
            this.btnEditar.setEnabled(false);
            this.btnNuevo.setEnabled(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        this.txtPersonal.setText("Nombres y Apellidos -Personal-");
        this.txtbuscar.setText(null);
        this.txtdes.setText("Ingrese descripcion...");
        this.tblRes.setModel(new DefaultTableModel());
        this.txtbuscar.requestFocus();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed
protected ImageIcon createImageIcon(String path,String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IUDevolucion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel btnId;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btndesarrollador;
    private javax.swing.JButton btndevolucion;
    private javax.swing.JButton btnlector;
    private javax.swing.JButton btnlibro;
    private javax.swing.JButton btnpersonal;
    private javax.swing.JButton btnprestamo;
    private javax.swing.JButton btnreportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblhora;
    private javax.swing.JTable tblRes;
    private com.guis.autotextfield.AutoTextField txtPersonal;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextArea txtdes;
    // End of variables declaration//GEN-END:variables

 
}