/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IULibro.java
 *
 * Created on 19-dic-2011, 10:57:37
 */
package GUIBiblioteca;

import Util.imgdetalles;
import java.awt.BorderLayout;
import java.net.URL;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Carlos J Medina
 */
public class IUDetalles extends javax.swing.JFrame {

private Reloj.Hora hora;
    /** Creates new form IULibro */
    public IUDetalles() {
        this.setUndecorated(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFecha = new javax.swing.JLabel();
        lblLibro = new javax.swing.JLabel();
        lblLector = new javax.swing.JLabel();
        btnProgress = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tbnEstado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblFecha.setText("14/11/1991                          18/11/1991");

        lblLibro.setText("Programacion Web PHP + SQL");

        lblLector.setText("Carlos Jhoel Medina Silvestre");

        btnProgress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnProgreso.png"))); // NOI18N
        btnProgress.setBorder(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnCerrar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tbnEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnEstado.png"))); // NOI18N
        tbnEstado.setBorder(null);
        tbnEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProgress)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLector, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(lblLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(tbnEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(tbnEstado))
                .addGap(18, 18, 18)
                .addComponent(lblLibro)
                .addGap(28, 28, 28)
                .addComponent(lblLector)
                .addGap(27, 27, 27)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnProgress))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        public static synchronized java.util.Date deStringToDate(String fecha) {
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaEnviar = null;
        try {
            fechaEnviar = formatoDelTexto.parse(fecha);
            return fechaEnviar;
        } catch (ParseException ex) {
            ex.printStackTrace();
            return null;
        }
        }
        
        public static java.util.Date sumarFechasDias(java.util.Date fch, int dias) {
        Calendar cal = new GregorianCalendar();
        cal.setTimeInMillis(fch.getTime());
        cal.add(Calendar.DATE, dias);
        return new java.util.Date(cal.getTimeInMillis());
        }
        
        public static synchronized int diferenciasDeFechas(Date fechaInicial, Date fechaFinal) {

        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String fechaInicioString = df.format(fechaInicial);
        try {
            fechaInicial = df.parse(fechaInicioString);
        } catch (ParseException ex) {
        }

        String fechaFinalString = df.format(fechaFinal);
        try {
            fechaFinal = df.parse(fechaFinalString);
        } catch (ParseException ex) {
        }

        long fechaInicialMs = fechaInicial.getTime();
        long fechaFinalMs = fechaFinal.getTime();
        long diferencia = fechaFinalMs - fechaInicialMs;
        double dias = Math.floor(diferencia / (1000 * 60 * 60 * 24));
        return ((int) dias);
    }
          
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imgdetalles p = new imgdetalles();
        this.add( p , BorderLayout.CENTER);
        p.repaint();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
                
        Date fecha1= this.deStringToDate(IUPrestamo.FechaPrestamo);
        Date fecha2= this.sumarFechasDias(fecha1, 3);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fecha3= formato.format(fecha2);
        Date  fechaActual=new Date();        
        int dias=diferenciasDeFechas(fecha1,fechaActual);
        String estado=IUPrestamo.Estado;
        this.lblLector.setText(IUPrestamo.NomLector);
        this.lblLibro.setText(IUPrestamo.NomLibro);
        this.lblFecha.setText(IUPrestamo.FechaPrestamo + "                          " + fecha3);       
        
        
        ImageIcon icon;
        if(dias==0){
        icon = createImageIcon("../Archivos/btnProgreso0.png","Boton para saber si esta disponible");
        }else if(dias==1){
        icon = createImageIcon("../Archivos/btnProgreso1.png","Boton para saber si esta disponible");
        }else if(dias==2){
        icon = createImageIcon("../Archivos/btnProgreso2.png","Boton para saber si esta disponible");
        }else{
        icon = createImageIcon("../Archivos/btnProgreso3.png","Boton para saber si esta disponible");
        }
        this.btnProgress.setIcon(icon);
        
        ImageIcon icon1;
        if("PENDIENTE".equals(estado)){
        icon1 = createImageIcon("../Archivos/btnEstado.png","Boton para saber si esta disponible");
        }else{
        icon1 = createImageIcon("../Archivos/btnEstado1.png","Boton para saber si esta disponible");
        }
        this.tbnEstado.setIcon(icon1);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnEstadoActionPerformed
protected ImageIcon createImageIcon(String path,String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("No se encuentra el archivo: " + path);
        return null;
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IUDetalles().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProgress;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLector;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JButton tbnEstado;
    // End of variables declaration//GEN-END:variables

}