/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IULibro.java
 *
 * Created on 19-dic-2011, 10:57:37
 */
package GUIBiblioteca;

import Util.imglector;
import java.awt.BorderLayout;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Datos.Lector;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Carlos J Medina
 */
public class IULector extends javax.swing.JFrame {

    int boton=0;
    static int indice;
    char accion;
    static int bola;//Creacion del Obj q permite crear la Coleccion y acceder a sus metodos en la clase "Curso"
    static Lector oLe= new Lector();
    static String cadenaFecha;
    
public void LimpiarCajas()
    {
        this.txtApellidos.setText(null);
        this.txtDNI.setText(null);
        this.txtDireccion.setText(null);
        this.txtID.setText(null);
        this.txtNombres.setText(null);
        this.txtTelefono.setText(null);
    }

public void ActivarCajas()
    {
        this.txtApellidos.setEnabled(true);
        this.txtDNI.setEnabled(true);
        this.txtDireccion.setEnabled(true);
        this.txtID.setEnabled(true);
        this.txtNombres.setEnabled(true);
        this.txtTelefono.setEnabled(true);
    }

public void DesactivarCajas()
    {
        this.txtApellidos.setEnabled(false);
        this.txtDNI.setEnabled(false);
        this.txtDireccion.setEnabled(false);
        this.txtID.setEnabled(false);
        this.txtNombres.setEnabled(false);
        this.txtTelefono.setEnabled(false);
    }

public void Actualizar()
    {
        this.lblRegistro.setText(String.valueOf(indice + 1) + " DE " + String.valueOf(oLe.obtenerCantidad()));
    }


public void Verificar(int bola){
         if(bola==1){
                ImageIcon icon = createImageIcon("../Archivos/activo.png","Boton para saber si esta disponible");
                this.lblbola.setIcon(icon);
            }else{
                ImageIcon icon = createImageIcon("../Archivos/no-activo.png","Boton para saber si esta disponible");   
                this.lblbola.setIcon(icon);
            }
}
    
public void BuscarXcodigo(String codigo){
    
        Lector lec=null;
                
        lec= oLe.buscarLecCod(codigo);
        
        if(lec!=null) {
            //Obtiene el indice del Obj. Curso almacenado en la coleccion(me va a servir luego para modificar)
            indice= oLe.obtenerIndice(lec);
            //Coloca en los componentes los datos extraidos de la Coleccion
            this.txtApellidos.setText(lec.getApe());
            this.txtDNI.setText(lec.getDni());
            this.txtDireccion.setText(lec.getDir());
            this.txtFecha.setText(lec.getFing());
            this.txtID.setText(lec.getId());
            this.txtNombres.setText(lec.getNom());
            this.txtTelefono.setText(lec.getTel());
            this.txtcodigo.setText(lec.getCodigo());
            this.btnGuardar.setEnabled(false);
            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            boton=2;
            accion='E';
            bola=lec.getActivo();
            Verificar(bola);
            this.txtbuscar.setText("Ingrese ID!");
           }else{
            this.txtbuscar.setText("No Existe!!!");
        }
        this.Actualizar();
}

private Reloj.Hora hora;
    /** Creates new form IULibro */
    public IULector() {
        this.setUndecorated(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnatras = new javax.swing.JButton();
        btnlibro = new javax.swing.JButton();
        btnpersonal = new javax.swing.JButton();
        btnprestamo = new javax.swing.JButton();
        btnlector = new javax.swing.JButton();
        btndevolucion = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        btndesarrollador = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblbola = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAtras.png"))); // NOI18N
        btnatras.setBorder(null);
        btnatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        btnlibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnlibro.setBorder(null);
        btnlibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibroActionPerformed(evt);
            }
        });

        btnpersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnpersonal.setBorder(null);
        btnpersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonalActionPerformed(evt);
            }
        });

        btnprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnprestamo.setBorder(null);
        btnprestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamoActionPerformed(evt);
            }
        });

        btnlector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuActivo.png"))); // NOI18N
        btnlector.setBorder(null);
        btnlector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlectorActionPerformed(evt);
            }
        });

        btndevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btndevolucion.setBorder(null);
        btndevolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndevolucionActionPerformed(evt);
            }
        });

        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnreportes.setBorder(null);
        btnreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        btndesarrollador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btndesarrollador.setBorder(null);
        btndesarrollador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnPrimero.png"))); // NOI18N
        btnPrimero.setBorder(null);
        btnPrimero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAnterior.png"))); // NOI18N
        btnAnterior.setBorder(null);
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSiguiente.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnUltimo.png"))); // NOI18N
        btnUltimo.setBorder(null);
        btnUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        lblRegistro.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblRegistro.setText("0 DE 0");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Direccion:");

        jLabel7.setText("DNI:");

        txtcodigo.setBackground(new java.awt.Color(125, 164, 186));
        txtcodigo.setBorder(null);
        txtcodigo.setEnabled(false);

        txtNombres.setBackground(new java.awt.Color(125, 164, 186));
        txtNombres.setBorder(null);
        txtNombres.setEnabled(false);
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        txtApellidos.setBackground(new java.awt.Color(125, 164, 186));
        txtApellidos.setBorder(null);
        txtApellidos.setEnabled(false);

        txtDireccion.setBackground(new java.awt.Color(125, 164, 186));
        txtDireccion.setBorder(null);
        txtDireccion.setEnabled(false);

        jLabel9.setText("Fecha Ingreso:");

        txtFecha.setBackground(new java.awt.Color(125, 164, 186));
        txtFecha.setBorder(null);
        txtFecha.setEnabled(false);

        txtID.setBackground(new java.awt.Color(125, 164, 186));
        txtID.setBorder(null);
        txtID.setEnabled(false);
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        jLabel11.setText("Telefono/Celular:");

        lblhora.setBackground(new java.awt.Color(255, 255, 255));
        lblhora.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblhora.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnBuscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtbuscar.setText("ID.......");
        txtbuscar.setBorder(null);
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnEditar.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setDisabledIcon(null);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnNuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setDisabledIcon(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnGuardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setDisabledIcon(null);
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnEliminar.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setDisabledIcon(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSalir.png"))); // NOI18N
        btnNuevo1.setBorder(null);
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        txtTelefono.setBackground(new java.awt.Color(125, 164, 186));
        txtTelefono.setBorder(null);
        txtTelefono.setEnabled(false);
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel8.setText("ID:");

        txtDNI.setBackground(new java.awt.Color(125, 164, 186));
        txtDNI.setBorder(null);
        txtDNI.setEnabled(false);
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        lblbola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/activo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnatras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnreportes)
                            .addComponent(btndevolucion)
                            .addComponent(btnlector)
                            .addComponent(btnprestamo)
                            .addComponent(btnpersonal)
                            .addComponent(btnlibro)
                            .addComponent(btndesarrollador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegistro)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrimero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUltimo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTelefono))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnNuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEditar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblbola)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnNuevo1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrimero)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)
                            .addComponent(btnUltimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRegistro)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBuscar)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblbola, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                .addComponent(btnlibro)))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpersonal)
                        .addGap(28, 28, 28)
                        .addComponent(btnprestamo)
                        .addGap(25, 25, 25)
                        .addComponent(btnlector)
                        .addGap(31, 31, 31)
                        .addComponent(btndevolucion)
                        .addGap(25, 25, 25)
                        .addComponent(btnreportes))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndesarrollador)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar))
                .addGap(172, 172, 172)
                .addComponent(btnNuevo1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imglector p = new imglector();
        this.add( p , BorderLayout.CENTER);
        p.repaint();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        // TODO add your handling code here:
        hora = new Reloj.Hora();/***Inicializar la variable hora***/
        hora.setBounds(0, 0, 150, 15);/*(Ubicacion en eje x, Ubicacion en eje y, Ancho, Alto)*/
       //hora.setFont(new Font("Trebuchet MS",java.awt.Font.BOLD, 10));/*Cambiamos la fuente, estilo y tamaño*/
        this.lblhora.add(hora);/*La agregamos al JFrame*/
        // TODO add your handling code here:
        
        
        Date  fechaActual=new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        cadenaFecha = formato.format(fechaActual);
        
        if (oLe.obtenerCantidad()==0){
        Lector l = new Lector("1","Carlos Jhoel","Medina Silvestre","La Esperanza","14/11/1991","47641184","000104593","948703839",1);
        oLe.agregarLector(l);
        }
        this.BuscarXcodigo("1");
    }//GEN-LAST:event_formWindowOpened

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        IUMenu menu=new IUMenu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        this.dispose();
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibroActionPerformed
       IULibro libro=new IULibro();
        libro.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnlibroActionPerformed

    private void btnlectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlectorActionPerformed

    private void btnpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonalActionPerformed
        IUPersonal personal=new IUPersonal();
        personal.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpersonalActionPerformed

    private void btnprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamoActionPerformed
        IUPrestamo prestamo=new IUPrestamo();
        prestamo.setVisible(true);
        this.setVisible(false);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnprestamoActionPerformed

    private void btndevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndevolucionActionPerformed
        IUDevolucion devolucion=new IUDevolucion();
        devolucion.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btndevolucionActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        IUReportes reportes=new IUReportes();
        reportes.setVisible(true);
        this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportesActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.ActivarCajas();
        this.LimpiarCajas();
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        boton=1;
        this.txtNombres.requestFocus();
        this.txtcodigo.setText(String.valueOf(oLe.obtenerCantidad() + 1));
        accion='N';
        this.txtFecha.setText(cadenaFecha);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (boton==1){
        this.DesactivarCajas();
        this.LimpiarCajas();
        this.btnGuardar.setEnabled(false);
        this.btnNuevo.setEnabled(true);
        boton=0;
        }else if (boton==2){
       
        String codigo,nom,ape,dir,fing,dni,id,tel;
        int activo;
        boolean ex;
        codigo=this.txtcodigo.getText();
        nom=this.txtNombres.getText();
        ape=this.txtApellidos.getText();
        dir=this.txtDireccion.getText();
        fing=this.txtFecha.getText();
        dni=this.txtDNI.getText();
        id=this.txtID.getText();
        tel=this.txtTelefono.getText();
        activo=1;
  
        //Creacion del Obj
        Lector l = new Lector(codigo,nom,ape,dir,fing,dni,id,tel,activo);

        //Verifica si se encontro al Objeto
        if(indice!=-1) {
                l.setActivo(0);
                ex= oLe.modificarLec(indice, l); //Modifica el Obj. en la Coleccion con el indice y el nuevo obj.
                if(ex==true) {
                IUMsg msg=new IUMsg();
                msg.setVisible(true);
                DesactivarCajas();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                this.LimpiarCajas();
                this.DesactivarCajas();
                this.btnGuardar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                }
        }
        else{
            IUMsg1 msg1=new IUMsg1();
            msg1.setVisible(true);
                }

     }
        this.BuscarXcodigo("1");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        Lector lec=null;
        String filtro=this.txtbuscar.getText();
        
        lec= oLe.buscarLecID(filtro);
        
        if(lec!=null) {
            //Obtiene el indice del Obj. Curso almacenado en la coleccion(me va a servir luego para modificar)
            indice= oLe.obtenerIndice(lec);
            //Coloca en los componentes los datos extraidos de la Coleccion
            
            this.txtApellidos.setText(lec.getApe());
            this.txtDNI.setText(lec.getDni());
            this.txtDireccion.setText(lec.getDir());
            this.txtFecha.setText(lec.getFing());
            this.txtID.setText(lec.getId());
            this.txtNombres.setText(lec.getNom());
            this.txtTelefono.setText(lec.getTel());
            this.txtcodigo.setText(lec.getCodigo());
            this.btnGuardar.setEnabled(false);
            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            bola=lec.getActivo();
            boton=2;
            accion='E';
            Verificar(bola);
            this.txtbuscar.setText("Ingrese ID!");
           }
        else
        {this.txtbuscar.setText("No Existe!!!");}
        
           this.BuscarXcodigo("1");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //Variables propias del metodo
        String codigo,nom,ape,dir,fing,dni,id,tel;
        int activo;
        boolean ex;
        codigo=this.txtcodigo.getText();
        nom=this.txtNombres.getText();
        ape=this.txtApellidos.getText();
        dir=this.txtDireccion.getText();
        fing=this.txtFecha.getText();
        dni=this.txtDNI.getText();
        id=this.txtID.getText();
        tel=this.txtTelefono.getText();
        activo=1;
  
        //Creacion del Obj
        Lector l = new Lector(codigo,nom,ape,dir,fing,dni,id,tel,activo);

        //***************************Guardar Empleado******************************
        if(accion=='N') {
            ex= oLe.agregarLector(l); //Guarda el obj. en la Coleccion
            if(ex==true) {
                IUMsg msg=new IUMsg();
                msg.setVisible(true);
                DesactivarCajas();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
            }
            else{
                 IUMsg1 msg1=new IUMsg1();
                 msg1.setVisible(true);
        }}

        //***************************Modifica Empleado*****************************
        if(accion=='E') {
            ex= oLe.modificarLec(indice, l); //Modifica el Obj. en la Coleccion con el indice y el nuevo obj.
            if(ex==true) {
                IUMsg msg=new IUMsg();
                msg.setVisible(true);
                DesactivarCajas();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
            }
            else
            {
             IUMsg1 msg1=new IUMsg1();
            msg1.setVisible(true);

            }
        }
            this.BuscarXcodigo("1");
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (accion=='E'){
        this.ActivarCajas();
        this.btnGuardar.setEnabled(true);
        this.btnEditar.setEnabled(false);
        this.btnNuevo.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        this.BuscarXcodigo("1");
    // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
            this.BuscarXcodigo(String.valueOf(indice));
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        this.BuscarXcodigo(String.valueOf(oLe.obtenerCantidad()));
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        this.BuscarXcodigo(String.valueOf(indice + 2));
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        txtbuscar.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)//crear evento de KeyListener
        {
            if (txtbuscar.getText().length()==9) {
            e.consume();}
            char c = e.getKeyChar();
            if (!((Character.isDigit(c)))){
                e.consume();
            }
        }});
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        txtTelefono.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            if (Character.isLetter(c)){
                e.consume();
            }
            }
        });
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        txtDNI.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)//crear evento de KeyListener
        {
            if (txtDNI.getText().length()==8) {
            e.consume();}
            char c = e.getKeyChar();
            if (!((Character.isDigit(c)))){
                e.consume();
            }
        }});        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        txtID.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)//crear evento de KeyListener
        {
            if (txtID.getText().length()==9) {
            e.consume();}
            char c = e.getKeyChar();
            if (!((Character.isDigit(c)))){
                e.consume();
            }
        }});
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        txtNombres.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)//crear evento de KeyListener
        {
            char c = e.getKeyChar();
            if (!((Character.isLetter(c)))){
                if (Character.isSpaceChar(c)){}else{
                e.consume();}
            }
        }});
    }//GEN-LAST:event_txtNombresKeyTyped

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed
protected ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IULector().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btndesarrollador;
    private javax.swing.JButton btndevolucion;
    private javax.swing.JButton btnlector;
    private javax.swing.JButton btnlibro;
    private javax.swing.JButton btnpersonal;
    private javax.swing.JButton btnprestamo;
    private javax.swing.JButton btnreportes;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblbola;
    private javax.swing.JLabel lblhora;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables

 
}