/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IULibro.java
 *
 * Created on 19-dic-2011, 10:57:37
 */
package GUIBiblioteca;

import Util.imglibro1;
import java.awt.BorderLayout;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Datos.Libro;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Carlos J Medina
 */
public class IULibro extends javax.swing.JFrame {

private Reloj.Hora hora;
    /** Creates new form IULibro */
    public IULibro() {
        this.setUndecorated(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnatras = new javax.swing.JButton();
        btnlibro = new javax.swing.JButton();
        btnpersonal = new javax.swing.JButton();
        btnprestamo = new javax.swing.JButton();
        btnlector = new javax.swing.JButton();
        btndevolucion = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        btndesarrollador = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPag = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtTema = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        btnDisponible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAtras.png"))); // NOI18N
        btnatras.setBorder(null);
        btnatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        btnlibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuActivo.png"))); // NOI18N
        btnlibro.setBorder(null);
        btnlibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibroActionPerformed(evt);
            }
        });

        btnpersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnpersonal.setBorder(null);
        btnpersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonalActionPerformed(evt);
            }
        });

        btnprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnprestamo.setBorder(null);
        btnprestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamoActionPerformed(evt);
            }
        });

        btnlector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnlector.setBorder(null);
        btnlector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlectorActionPerformed(evt);
            }
        });

        btndevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btndevolucion.setBorder(null);
        btndevolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndevolucionActionPerformed(evt);
            }
        });

        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnreportes.setBorder(null);
        btnreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        btndesarrollador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btndesarrollador.setBorder(null);
        btndesarrollador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnPrimero.png"))); // NOI18N
        btnPrimero.setBorder(null);
        btnPrimero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAnterior.png"))); // NOI18N
        btnAnterior.setBorder(null);
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSiguiente.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnUltimo.png"))); // NOI18N
        btnUltimo.setBorder(null);
        btnUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        lblRegistro.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblRegistro.setText("0 DE 0");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Título:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Editorial:");

        jLabel6.setText("Nº pag:");

        jLabel7.setText("Tema:");

        txtcodigo.setBackground(new java.awt.Color(125, 164, 186));
        txtcodigo.setBorder(null);
        txtcodigo.setEnabled(false);

        txtTitulo.setBackground(new java.awt.Color(125, 164, 186));
        txtTitulo.setBorder(null);
        txtTitulo.setEnabled(false);
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });

        txtAutor.setBackground(new java.awt.Color(125, 164, 186));
        txtAutor.setBorder(null);
        txtAutor.setEnabled(false);
        txtAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAutorKeyTyped(evt);
            }
        });

        txtEditorial.setBackground(new java.awt.Color(125, 164, 186));
        txtEditorial.setBorder(null);
        txtEditorial.setEnabled(false);

        jLabel9.setText("Fecha Ingreso:");

        txtPag.setBackground(new java.awt.Color(125, 164, 186));
        txtPag.setBorder(null);
        txtPag.setEnabled(false);
        txtPag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagKeyTyped(evt);
            }
        });

        txtFecha.setBackground(new java.awt.Color(125, 164, 186));
        txtFecha.setBorder(null);
        txtFecha.setEnabled(false);

        txtTema.setBackground(new java.awt.Color(125, 164, 186));
        txtTema.setBorder(null);
        txtTema.setEnabled(false);

        jLabel11.setText("Disponible:");

        lblhora.setBackground(new java.awt.Color(255, 255, 255));
        lblhora.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblhora.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnBuscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtbuscar.setText("Ingrese Codigo...");
        txtbuscar.setBorder(null);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnEditar.png"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnNuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnGuardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setDisabledIcon(null);
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnEliminar.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setDisabledIcon(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSalir.png"))); // NOI18N
        btnNuevo1.setBorder(null);
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        btnDisponible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnOn.png"))); // NOI18N
        btnDisponible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDisponible.setEnabled(false);
        btnDisponible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisponibleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnatras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnreportes)
                            .addComponent(btndevolucion)
                            .addComponent(btnlector)
                            .addComponent(btnprestamo)
                            .addComponent(btnpersonal)
                            .addComponent(btnlibro)
                            .addComponent(btndesarrollador))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtTema, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtPag, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtFecha))
                                                .addComponent(txtEditorial, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscar))
                                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRegistro)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPrimero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAnterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSiguiente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUltimo))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnDisponible))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEditar)
                                        .addGap(10, 10, 10)
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btnNuevo1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrimero)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)
                            .addComponent(btnUltimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRegistro)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnlibro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnpersonal)
                        .addGap(28, 28, 28)
                        .addComponent(btnprestamo)
                        .addGap(25, 25, 25)
                        .addComponent(btnlector)
                        .addGap(31, 31, 31)
                        .addComponent(btndevolucion)
                        .addGap(25, 25, 25)
                        .addComponent(btnreportes))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPag, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(btnDisponible))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btndesarrollador)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo))
                .addGap(174, 174, 174)
                .addComponent(btnNuevo1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int boton=0;
    static int indice;
    char accion;
    static Libro oLi= new Libro();
    static boolean dis=true;
    static String cadenaFecha;
    
    public void LimpiarCajas()
    {
        this.txtAutor.setText(null);
        this.txtEditorial.setText(null);
        this.txtPag.setText(null);
        this.txtTema.setText(null);
        this.txtTitulo.setText(null);
    }

    public void ActivarCajas()
    {
        this.txtAutor.setEnabled(true);
        this.txtEditorial.setEnabled(true);
        this.txtPag.setEnabled(true);
        this.txtTema.setEnabled(true);
        this.txtTitulo.setEnabled(true);
        this.btnDisponible.setEnabled(true);
    }

    public void DesactivarCajas()
    {
        this.txtAutor.setEnabled(false);
        this.txtEditorial.setEnabled(false);
        this.txtPag.setEnabled(false);
        this.txtTema.setEnabled(false);
        this.txtTitulo.setEnabled(false);
        this.btnDisponible.setEnabled(false);
    }
    public void Verificar(boolean valor){
         if(valor==true){
                ImageIcon icon = createImageIcon("../Archivos/btnOn.png","Boton para saber si esta disponible");
                this.btnDisponible.setIcon(icon);
            }else{
                ImageIcon icon = createImageIcon("../Archivos/btnOff.png","Boton para saber si esta disponible");   
                this.btnDisponible.setIcon(icon);
            }
}
    
    public void Actualizar()
    {
        this.lblRegistro.setText(String.valueOf(indice + 1) + " DE " + String.valueOf(oLi.obtenerCantidad()));
    }
    
    public void BuscarXcodigo(String cod){

        Libro lib=null;
        lib= oLi.buscarLibCod(cod);
       
        if(lib!=null) {
            //Obtiene el indice del Obj. Curso almacenado en la coleccion(me va a servir luego para modificar)
            indice= oLi.obtenerIndice(lib);
            //Coloca en los componentes los datos extraidos de la Coleccion
            
            this.txtAutor.setText(lib.getAut());
            this.txtEditorial.setText(lib.getEdi());
            this.txtPag.setText(lib.getNpag());
            this.txtTema.setText(lib.getTema());
            this.txtTitulo.setText(lib.getTit());
            this.txtcodigo.setText(lib.getCodigo());
            this.txtFecha.setText(lib.getFing());
            dis=lib.isDis();
            this.btnGuardar.setEnabled(false);
            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            boton=2;
            accion='E';
            this.Verificar(dis);
            this.txtbuscar.setText("Ingrese Codigo!!!");
         }else{
            this.txtbuscar.setText("No Existe!!!");
         }
        Actualizar();
    }
    
    private int estado=1;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imglibro1 p = new imglibro1();
        this.add( p , BorderLayout.CENTER);
        p.repaint();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        // TODO add your handling code here:
        hora = new Reloj.Hora();/***Inicializar la variable hora***/
        hora.setBounds(0, 0, 150, 15);/*(Ubicacion en eje x, Ubicacion en eje y, Ancho, Alto)*/
       //hora.setFont(new Font("Trebuchet MS",java.awt.Font.BOLD, 10));/*Cambiamos la fuente, estilo y tamaño*/
        this.lblhora.add(hora);/*La agregamos al JFrame*/
        
        Date  fechaActual=new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        cadenaFecha = formato.format(fechaActual);
        
        if (oLi.obtenerCantidad()==0){
        Libro l = new Libro("1","PHP y Mysql - Programacion Web","Olivier HEURTEL","Ediciones Eni","345","19/11/2011","Programacion Web",true);
        oLi.agregarLibro(l);
        }
        this.BuscarXcodigo("1");
    }//GEN-LAST:event_formWindowOpened

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        IUMenu menu=new IUMenu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        this.dispose();
        System.exit(0);

    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnDisponibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisponibleMouseClicked
        if (estado==1){
        ImageIcon icon = createImageIcon("../Archivos/btnOff.png","Boton para saber si esta disponible");
        this.btnDisponible.setIcon(icon);
        estado=0;
        dis=false;
        }else{
        ImageIcon icon = createImageIcon("../Archivos/btnOn.png","Boton para saber si esta disponible");
        this.btnDisponible.setIcon(icon);
        estado=1;
        dis=true;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisponibleMouseClicked

    private void btnlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlibroActionPerformed

    private void btnpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonalActionPerformed
       IUPersonal personal=new IUPersonal();
        personal.setVisible(true);
        this.setVisible(false);
        this.dispose();
        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btnpersonalActionPerformed

    private void btnlectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlectorActionPerformed
        IULector lector=new IULector();
        lector.setVisible(true);
        this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnlectorActionPerformed

    private void btnprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamoActionPerformed
        IUPrestamo prestamo=new IUPrestamo();
        prestamo.setVisible(true);
        this.setVisible(false);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnprestamoActionPerformed

    private void btndevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndevolucionActionPerformed
        IUDevolucion devolucion=new IUDevolucion();
        devolucion.setVisible(true);
        this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btndevolucionActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        IUReportes reportes=new IUReportes();
        reportes.setVisible(true);
        this.setVisible(false);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnreportesActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.ActivarCajas();
        this.LimpiarCajas();
        this.btnGuardar.setEnabled(true);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        boton=1;
        this.txtTitulo.requestFocus();
        this.txtcodigo.setText(String.valueOf(oLi.obtenerCantidad() + 1));
        accion='N';
        this.txtFecha.setText(cadenaFecha);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.DesactivarCajas();
        this.LimpiarCajas();
        this.btnGuardar.setEnabled(false);
        this.btnNuevo.setEnabled(true);
        this.BuscarXcodigo("1");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
             //Variables propias del metodo
        String codigo,tit,aut,edi,npag,fing,tema;
  
        boolean ex;
        codigo=this.txtcodigo.getText();
        tit=this.txtTitulo.getText();
        aut=this.txtAutor.getText();
        edi=this.txtEditorial.getText();
        npag=this.txtPag.getText();
        fing=this.txtFecha.getText();
        tema=this.txtTema.getText();

        //Creacion del Obj
        Libro l = new Libro(codigo,tit,aut,edi,npag,fing,tema,dis);

        //***************************Guardar Empleado******************************
        if(accion=='N') {
            ex= oLi.agregarLibro(l); //Guarda el obj. en la Coleccion
            if(ex==true) {
                IUMsg msg=new IUMsg();
                msg.setVisible(true);
                DesactivarCajas();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
            }else{
                 IUMsg1 msg1=new IUMsg1();
                 msg1.setVisible(true);
            }
        
        }
        //***************************Modifica Empleado*****************************
        if(accion=='E') {
            ex= oLi.modificarLib(indice, l); //Modifica el Obj. en la Coleccion con el indice y el nuevo obj.
            if(ex==true) {
                IUMsg msg=new IUMsg();
                msg.setVisible(true);
                DesactivarCajas();
                this.btnGuardar.setEnabled(false);
                this.btnEditar.setEnabled(false);
                this.btnNuevo.setEnabled(true);
            }
            else
            {
            IUMsg1 msg1=new IUMsg1();
            msg1.setVisible(true);
            }
        }
        
        this.BuscarXcodigo("1");
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (accion=='E'){
        this.ActivarCajas();
        this.btnGuardar.setEnabled(true);
        this.btnEditar.setEnabled(false);
        this.btnNuevo.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Libro lib=null;
        String filtro=this.txtbuscar.getText();
        
        lib= oLi.buscarLibCod(filtro);
        
        if(lib!=null) {
            //Obtiene el indice del Obj. Curso almacenado en la coleccion(me va a servir luego para modificar)
            indice= oLi.obtenerIndice(lib);
            //Coloca en los componentes los datos extraidos de la Coleccion
            
            this.txtAutor.setText(lib.getAut());
            this.txtEditorial.setText(lib.getEdi());
            this.txtFecha.setText(lib.getFing());
            this.txtPag.setText(lib.getNpag());
            this.txtTema.setText(lib.getTema());
            this.txtTitulo.setText(lib.getTit());
            this.txtcodigo.setText(lib.getCodigo());
            dis=lib.isDis();
            this.btnGuardar.setEnabled(false);
            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            boton=2;
            accion='E';
            this.Verificar(dis);
            this.txtbuscar.setText("Ingrese Codigo!!!");
         }else{
            this.txtbuscar.setText("No Existe!!!");
        }
            Actualizar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        this.BuscarXcodigo("1");        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        this.BuscarXcodigo(String.valueOf(indice));
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        this.BuscarXcodigo(String.valueOf(oLi.obtenerCantidad()));
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        this.BuscarXcodigo(String.valueOf(indice + 2));
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloKeyTyped

    private void txtAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutorKeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorKeyTyped

    private void txtPagKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagKeyTyped
        txtPag.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e)//crear evento de KeyListener
        {
            char c = e.getKeyChar();
            if (!((Character.isDigit(c)))){
                e.consume();
            
        }}});        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagKeyTyped
protected ImageIcon createImageIcon(String path,
    String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("No se encuentra el archivo: " + path);
        return null;
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IULibro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel btnDisponible;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btndesarrollador;
    private javax.swing.JButton btndevolucion;
    private javax.swing.JButton btnlector;
    private javax.swing.JButton btnlibro;
    private javax.swing.JButton btnpersonal;
    private javax.swing.JButton btnprestamo;
    private javax.swing.JButton btnreportes;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblhora;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPag;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables

}