/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IULibro.java
 *
 * Created on 19-dic-2011, 10:57:37
 */
package GUIBiblioteca;

import Util.imgprestamo;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import Datos.Prestamo;
import Datos.Lector;
import Datos.Libro;
import Datos.Personal;
import java.util.ArrayList;

/**
 *
 * @author Carlos J Medina
 */
public class IUPrestamo extends javax.swing.JFrame {

    static String cadenaFecha;
    static Prestamo oPr= new Prestamo();
    static int indice;
    static int indicel;
    static Libro lib=null;
    
    static String NomLector;
    static String NomLibro;
    static String FechaPrestamo;
    static String Libro1;
    static String Estado;
    
    ArrayList libros = new ArrayList();
    ArrayList libros1 = new ArrayList();
    ArrayList empleado = new ArrayList();
    
private Reloj.Hora hora;
    /** Creates new form IULibro */
    public IUPrestamo() {
        this.setUndecorated(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnatras = new javax.swing.JButton();
        btnlibro = new javax.swing.JButton();
        btnpersonal = new javax.swing.JButton();
        btnprestamo = new javax.swing.JButton();
        btnlector = new javax.swing.JButton();
        btndevolucion = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        btndesarrollador = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lblhora = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtfiltro1 = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtlector = new javax.swing.JTextField();
        btnTit = new javax.swing.JLabel();
        btnId = new javax.swing.JLabel();
        txtfiltro2 = new com.guis.autotextfield.AutoTextField();
        txtempleado = new com.guis.autotextfield.AutoTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAtras.png"))); // NOI18N
        btnatras.setBorder(null);
        btnatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        btnlibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnlibro.setBorder(null);
        btnlibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibroActionPerformed(evt);
            }
        });

        btnpersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnpersonal.setBorder(null);
        btnpersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpersonalActionPerformed(evt);
            }
        });

        btnprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuActivo.png"))); // NOI18N
        btnprestamo.setBorder(null);
        btnprestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprestamoActionPerformed(evt);
            }
        });

        btnlector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnlector.setBorder(null);
        btnlector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlectorActionPerformed(evt);
            }
        });

        btndevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btndevolucion.setBorder(null);
        btndevolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndevolucionActionPerformed(evt);
            }
        });

        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btnreportes.setBorder(null);
        btnreportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportesActionPerformed(evt);
            }
        });

        btndesarrollador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnMenuNoActivo.png"))); // NOI18N
        btndesarrollador.setBorder(null);
        btndesarrollador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnPrimero.png"))); // NOI18N
        btnPrimero.setBorder(null);
        btnPrimero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnAnterior.png"))); // NOI18N
        btnAnterior.setBorder(null);
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSiguiente.png"))); // NOI18N
        btnSiguiente.setBorder(null);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnUltimo.png"))); // NOI18N
        btnUltimo.setBorder(null);
        btnUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        lblRegistro.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        lblRegistro.setText("0 DE 0");

        jLabel2.setText("Nº Ficha:");

        txtcodigo.setBackground(new java.awt.Color(125, 164, 186));
        txtcodigo.setText("10");
        txtcodigo.setBorder(null);
        txtcodigo.setEnabled(false);

        lblhora.setBackground(new java.awt.Color(255, 255, 255));
        lblhora.setFont(new java.awt.Font("Tahoma", 0, 10));
        lblhora.setForeground(new java.awt.Color(255, 255, 255));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnGuardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnNuevo.png"))); // NOI18N
        btnNuevo.setBorder(null);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setDisabledIcon(null);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnDetalles.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnSalir.png"))); // NOI18N
        btnNuevo1.setBorder(null);
        btnNuevo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha:");

        txtFecha.setBackground(new java.awt.Color(125, 164, 186));
        txtFecha.setText("14/11/1991");
        txtFecha.setBorder(null);
        txtFecha.setEnabled(false);

        txtfiltro1.setText("Ingrese ID...!!!");
        txtfiltro1.setBorder(null);
        txtfiltro1.setEnabled(false);

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnBuscar.png"))); // NOI18N
        btnbuscar.setBorder(null);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.setEnabled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtlector.setBackground(new java.awt.Color(125, 164, 186));
        txtlector.setBorder(null);
        txtlector.setEnabled(false);

        btnTit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnTit1.png"))); // NOI18N
        btnTit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTitMouseClicked(evt);
            }
        });

        btnId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/btnDoc1.png"))); // NOI18N
        btnId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnId.setEnabled(false);
        btnId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIdMouseClicked(evt);
            }
        });

        txtfiltro2.setBackground(new java.awt.Color(51, 204, 255));
        txtfiltro2.setText("Ingrese iniciales para empezar a filtrar");
        txtfiltro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfiltro2MouseClicked(evt);
            }
        });

        txtempleado.setText("Ingrese iniciales para empezar a filtrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnatras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnreportes)
                            .addComponent(btndevolucion)
                            .addComponent(btnlector)
                            .addComponent(btnprestamo)
                            .addComponent(btnpersonal)
                            .addComponent(btnlibro)
                            .addComponent(btndesarrollador))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblRegistro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPrimero))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAnterior)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSiguiente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUltimo)
                                                .addGap(12, 12, 12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnNuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbuscar))
                                    .addComponent(txtfiltro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtlector, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(txtempleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnTit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnNuevo1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrimero)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)
                            .addComponent(btnUltimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRegistro)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnlibro)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnpersonal)
                        .addGap(28, 28, 28)
                        .addComponent(btnprestamo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnId)
                            .addComponent(btnbuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtlector, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnlector)
                    .addComponent(btnTit))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btndevolucion)
                        .addGap(25, 25, 25)
                        .addComponent(btnreportes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtfiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndesarrollador)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo)
                    .addComponent(btnEliminar))
                .addGap(171, 171, 171)
                .addComponent(btnNuevo1)
                .addContainerGap())
        );

        lblRegistro.getAccessibleContext().setAccessibleName("1 DE 0");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private int estado=1;
    private int estado1=1;
    
    public void Actualizar()
    {
        this.lblRegistro.setText(String.valueOf(indice + 1) + " DE " + String.valueOf(oPr.obtenerCantidad()));
    }
    
    public void BuscarXcodigo(String codigo){
    
        Prestamo pre=null;
                
        pre= oPr.buscarPreCod(codigo);
        
        if(pre!=null) {
            indice= oPr.obtenerIndice(pre);
            //Coloca en los componentes los datos extraidos de la Coleccion
            this.txtcodigo.setText(pre.getFicha());
            this.txtFecha.setText(pre.getFecha());
            this.txtlector.setText(pre.getLector());
            this.txtfiltro2.setText(pre.getLibro());
            this.txtempleado.setText(pre.getPersonal());
            this.btnGuardar.setEnabled(false);
            this.btnNuevo.setEnabled(true);
            NomLector=pre.getLector();
            NomLibro=pre.getLibro();
            FechaPrestamo=pre.getFecha();
            Estado=pre.getEstado();
        }
            Actualizar();
}
    
    public void Iniciar(){
     
        int j,k;
        j=1;
        k=1;
               
        while ( j <= IUPersonal.oPe.obtenerCantidad() ) {
            Personal per=null;
            per= IUPersonal.oPe.buscarPerCod(String.valueOf(j));
            if(per!=null) {
                empleado.add(per.getNom() + " " + per.getApe());
            }
            j++;
        }

        while ( k <= IULibro.oLi.obtenerCantidad() ) {
            lib= IULibro.oLi.buscarLibCod(String.valueOf(k));
            if(lib!=null) {
                indicel=IULibro.oLi.obtenerIndice(lib);
                if(lib.isDis()==true){
                libros.add(lib.getTit() + "-" + lib.getAut());
                }
            }
            k++;
        }
  
        this.txtempleado.setItems(empleado);
        
        this.txtfiltro2.setItems(libros);
        

    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imgprestamo p = new imgprestamo();
        this.add( p , BorderLayout.CENTER);
        p.repaint();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        hora = new Reloj.Hora();/***Inicializar la variable hora***/
        hora.setBounds(0, 0, 150, 15);/*(Ubicacion en eje x, Ubicacion en eje y, Ancho, Alto)*/
       //hora.setFont(new Font("Trebuchet MS",java.awt.Font.BOLD, 10));/*Cambiamos la fuente, estilo y tamaño*/
        this.lblhora.add(hora);/*La agregamos al JFrame*/
        Iniciar();
        Date  fechaActual=new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        cadenaFecha = formato.format(fechaActual);
        
        if (oPr.obtenerCantidad()==0){
            Prestamo pre = new Prestamo("1","01/01/2012","Carlos Jhoel Medina Silvestre","PHP y Mysql - Programacion Web - Olivier HEURTEL","Steven Paul Jobs","PENDIENTE");
            oPr.agregarPrestamo(pre);
        }
        
        this.BuscarXcodigo("1");
    }//GEN-LAST:event_formWindowOpened

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        IUMenu menu=new IUMenu();
        menu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibroActionPerformed
       IULibro libro=new IULibro();
        libro.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnlibroActionPerformed

    private void btnpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersonalActionPerformed
        IUPersonal personal=new IUPersonal();
        personal.setVisible(true);
        this.setVisible(false);
        this.dispose();  
    }//GEN-LAST:event_btnpersonalActionPerformed

    private void btnlectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlectorActionPerformed
        IULector lector=new IULector();
        lector.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnlectorActionPerformed

    private void btnIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdMouseClicked
        if (estado==1){
            ImageIcon icon = createImageIcon("../Archivos/btnDoc.png","Boton para saber si esta disponible");
            this.btnId.setIcon(icon);
            estado=0;
            this.txtfiltro1.setText("Ingrese DNI...!!!");
        }else{
            ImageIcon icon = createImageIcon("../Archivos/btnDoc1.png","Boton para saber si esta disponible");
            this.btnId.setIcon(icon);
            estado=1;
            this.txtfiltro1.setText("Ingrese ID...!!!");
        }
    }//GEN-LAST:event_btnIdMouseClicked

    private void btnTitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTitMouseClicked

    }//GEN-LAST:event_btnTitMouseClicked

    private void btnprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprestamoActionPerformed

    }//GEN-LAST:event_btnprestamoActionPerformed

    private void btndevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndevolucionActionPerformed
        IUDevolucion devolucion=new IUDevolucion();
        devolucion.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btndevolucionActionPerformed

    private void btnreportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportesActionPerformed
        IUReportes reportes=new IUReportes();
        reportes.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnreportesActionPerformed

    private void txtfiltro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfiltro2MouseClicked
    }//GEN-LAST:event_txtfiltro2MouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.txtfiltro1.setEnabled(true);
        this.txtfiltro2.setEnabled(true);
        this.txtempleado.setEnabled(true);
        this.btnId.setEnabled(true);
        this.btnTit.setEnabled(true);
        this.btnGuardar.setEnabled(true);
        this.btnbuscar.setEnabled(true);
        this.txtFecha.setText(cadenaFecha);
        this.txtcodigo.setText(String.valueOf(oPr.obtenerCantidad() + 1));
        this.txtempleado.setText(null);
        this.txtfiltro1.setText(null);
        this.txtfiltro2.setText(null);
        this.txtlector.setText(null);
        this.btnEliminar.setEnabled(false);
        this.txtfiltro1.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        IUDetalles det=new IUDetalles();
        det.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        Lector lec=null;
        
        String filtro=this.txtfiltro1.getText();
        
        if (estado==1){
            lec= IULector.oLe.buscarLecID(filtro);
        }else{
            lec= IULector.oLe.buscarLecDNI(filtro);     
        }
        if(lec!=null) {
        
            this.txtlector.setText(lec.getNom() + " " + lec.getApe());
   
        }else{
            this.txtlector.setText("error");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        this.BuscarXcodigo("1");
        
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        this.BuscarXcodigo(String.valueOf(indice));        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        this.BuscarXcodigo(String.valueOf(oPr.obtenerCantidad()));        // TODO add your handling code here:
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        this.BuscarXcodigo(String.valueOf(indice + 2));        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String codigo,fecha,lectorA,libroA,person;
        boolean ex;
        codigo=this.txtcodigo.getText();
        fecha=this.txtFecha.getText();
        lectorA=this.txtlector.getText();
        libroA=this.txtfiltro2.getText();
        person=this.txtempleado.getText();
  
        //Creacion del Obj
        Prestamo p = new Prestamo(codigo,fecha,lectorA,libroA,person,"PENDIENTE");
        ex= oPr.agregarPrestamo(p); //Guarda el obj. en la Coleccion
            
        if(ex==true) {
                lib.setDis(false);
                IULibro.oLi.modificarLib(indice, lib);
                IUMsg msg=new IUMsg();
                msg.setVisible(true);
                this.btnGuardar.setEnabled(false);
                this.btnEliminar.setEnabled(true);
                this.btnNuevo.setEnabled(true);
        }
            else{
                 IUMsg1 msg1=new IUMsg1();
                 msg1.setVisible(true);
        }
        
        this.BuscarXcodigo("1");
    }//GEN-LAST:event_btnGuardarActionPerformed
protected ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IUPrestamo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel btnId;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel btnTit;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btndesarrollador;
    private javax.swing.JButton btndevolucion;
    private javax.swing.JButton btnlector;
    private javax.swing.JButton btnlibro;
    private javax.swing.JButton btnpersonal;
    private javax.swing.JButton btnprestamo;
    private javax.swing.JButton btnreportes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblhora;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtcodigo;
    private com.guis.autotextfield.AutoTextField txtempleado;
    private javax.swing.JTextField txtfiltro1;
    private com.guis.autotextfield.AutoTextField txtfiltro2;
    private javax.swing.JTextField txtlector;
    // End of variables declaration//GEN-END:variables
}